language: python
# Keep up to date with the tox.ini list
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
install:
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
script:
  - make test
after_success:
  - coveralls
sudo: false
