language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# Keep up to date with the tox.ini list
env:
  - TOXENV=py27
  - TOXENV=py34
install:
  - "pip install coveralls tox --use-mirrors"
script:
  - make build
  - make test
after_success:
  - coveralls
sudo: false
